version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - '8080:80'
  scraper:
    build:
      dockerfile: Dockerfile.dev
      context: './scraper'
    volumes:
      - /app/node_modules
      - ./scraper:/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  api:
    build:
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app